# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 16005b9ada88f891acf58fab5673d2d6e952584f981ab5f2495b0cc0738e9fd082aa6cfe6358acab229f0e61685fcce963b6bfc95c67304ce1f8aeef6882f162

test:
  secret_key_base: 99115808738ba958a23ca8e31d7db439e70bc0910e1a727ae7da5d5361054ef8ab9895d7260a683c360c5cf38a96fb8a3e421429f3dd2fe4aad7809953148571

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
